GeoCodingTest/Controllers/GeoCodingController.cs
using CrystalDecisions.CrystalReports.Engine;
using GeoCodingTest.Class;
using GeoCodingTest.Models.L1;
using GeoCodingTest.Models.L2;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Validation;
using System.DirectoryServices;
using System.DirectoryServices.AccountManagement;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Text;
using static GeoCodingTest.Models.L2.DBSWGE2;


namespace GeoCodingTest.Controllers
{
    public class GeoCodingController : Controller
    {
        InterfaceLog log = new InterfaceLog(ConfigurationManager.AppSettings["LogsPath"]);
        //DateTime date2020 = new DateTime(2020, 07, 01);
        DateTime date2020 = DateTime.ParseExact(ConfigurationManager.AppSettings["Date"], "yyyy-MM-dd", CultureInfo.InvariantCulture);
        DateTime timenow = DateTime.Now;

        /*private void LineNotify(string lineToken, string message)
        {
            try
            {
                message = System.Web.HttpUtility.UrlEncode(message, Encoding.UTF8);
                var request = (HttpWebRequest)WebRequest.Create("https://notify-api.line.me/api/notify");
                var postData = string.Format("message={0}", message);
                var data = Encoding.UTF8.GetBytes(postData);
                request.Method = "POST";
                request.ContentType = "application/x-www-form-urlencoded";
                request.ContentLength = data.Length;
                request.Headers.Add("Authorization", "Bearer " + lineToken);
                var stream = request.GetRequestStream();
                stream.Write(data, 0, data.Length);
                var response = (HttpWebResponse)request.GetResponse();
                var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }
        */
        /***********************************Module นี้ ไม่ได้ใช้ **************************/
        [HttpPost]
        public ActionResult getLocation(string location)
        {
            if (Session["Name"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            try
            {
                string[] location1 = location.Split(',');
                string[] latitude1 = location1[0].Split(':');
                string[] longitude1 = location1[1].Split(':');
                string cardcode1 = location1[3];
                string cardname1 = location1[4];
                int invno1 = Convert.ToInt32(location1[5]);

                string[] datebillcheck = location1[6].Split(' ');
                int datebillcheck1 = datebillcheck[0].Count();
                string[] duedatebillcheck = location1[8].Split(' ');
                int duedatebillcheck1 = duedatebillcheck[0].Count();

                string datebill1 = location1[6];
                string duedatebill1 = location1[8];
                string datebill2;
                DateTime datebill3;
                string duedatebill2;
                DateTime duedatebill3;

                if (datebill1.Contains("AM") == true)
                {
                    datebill2 = datebill1.Substring(0, datebillcheck1);
                    datebill3 = DateTime.ParseExact(datebill2, "M/d/yyyy", CultureInfo.InvariantCulture);

                    duedatebill2 = duedatebill1.Substring(0, duedatebillcheck1);
                    duedatebill3 = DateTime.ParseExact(duedatebill2, "M/d/yyyy", CultureInfo.InvariantCulture);
                }
                else
                {
                    datebill2 = datebill1.Substring(0, 10);
                    datebill3 = DateTime.ParseExact(datebill2, "dd/MM/yyyy", CultureInfo.InvariantCulture);

                    duedatebill2 = duedatebill1.Substring(0, 10);
                    duedatebill3 = DateTime.ParseExact(duedatebill2, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                }

                decimal total1 = Convert.ToDecimal(location1[7]);

                string name1 = location1[9];
                int code1 = Convert.ToInt32(location1[10]);
                int typeid1 = Convert.ToInt32(location1[11]);

                using (var db = new DBS_WGE_Entities())
                {

                    LocationTest lt = new LocationTest();
                    lt.Latitude = latitude1[1];
                    lt.Longitude = longitude1[1];
                    lt.CardCode = cardcode1;
                    lt.CardName = cardname1;
                    lt.InvNo = invno1;
                    lt.DateBill = datebill3;
                    lt.Total = total1;
                    lt.DueDateBill = duedatebill3;
                    lt.Name = name1;
                    lt.Code = code1;
                    lt.TypeID = typeid1;
                    lt.SubmitDate = DateTime.Now;

                    db.LocationTest.Add(lt);
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                log.WriteLog(ex.Message.ToString());
            }


            return RedirectToAction("Index");
        }
        /***********************************Module นี้ ไม่ได้ใช้ **************************/
        // GET: GeoCoding
        public ActionResult ViewTest()
        {
            return View();
        }
        /***********************************Module นี้ ไม่ได้ใช้ **************************/
        public ActionResult Bill1()
        {
            if (Session["Name"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            mWGE mwge = new mWGE();
            Session["TypeID"] = "1";
            return View(mwge);
        }
        /***********************************Module นี้ ไม่ได้ใช้ **************************/
        [HttpPost]
        public ActionResult Bill1(int invoiceno, mWGE mData)
        {
            if (Session["Name"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            try
            {
                using (var db = new DBS_WGE_Entities())
                {
                    var oData = (from a in db.OINV
                                 join b in db.OSLP on a.SlpCode equals b.SlpCode into bb
                                 from b in bb.DefaultIfEmpty()
                                 join c in db.OCRD on a.CardCode equals c.CardCode into cc
                                 from c in cc.DefaultIfEmpty()
                                 where 1 == 1
                                 select new OINV2
                                 {
                                     CardCode = a.CardCode,
                                     CardName = a.CardName,
                                     InvNo = a.DocNum,
                                     DateBill = a.DocDate,
                                     DueDateBill = a.DocDueDate,
                                     Total = a.DocTotalSy - a.PaidSys
                                 });

                    var oData2 = (from e in db.ORIN
                                  join f in db.OSLP on e.SlpCode equals f.SlpCode into ff
                                  from f in ff.DefaultIfEmpty()
                                  join g in db.OCRD on e.CardCode equals g.CardCode into gg
                                  from g in gg.DefaultIfEmpty()
                                  where 1 == 1
                                  select new OINV2
                                  {
                                      CardCode = e.CardCode,
                                      CardName = e.CardName,
                                      InvNo = e.DocNum,
                                      DateBill = e.DocDate,
                                      DueDateBill = e.DocDueDate,
                                      Total = e.DocTotalSy - e.PaidSys
                                  });

                    var allData = oData.Concat(oData2);

                    if (!string.IsNullOrEmpty(mData.DocNum.ToString()))
                    {
                        allData = allData.Where(a => a.InvNo == invoiceno);
                    }
                    if (allData != null)
                    {
                        mData.ListOINV = allData.ToList();
                    }
                }
            }
            catch (Exception ex)
            {
                log.WriteLog(ex.Message.ToString());
            }

            return View(mData);
        }
        /***********************************Module นี้ ไม่ได้ใช้ **************************/
        public ActionResult Bill2()
        {
            if (Session["Name"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            mWGE mwge = new mWGE();
            Session["TypeID"] = "2";
            return View(mwge);
        }
        /***********************************Module นี้ ไม่ได้ใช้ **************************/
        [HttpPost]
        public ActionResult Bill2(int invoiceno, mWGE mData)
        {
            if (Session["Name"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            try
            {
                using (var db = new DBS_WGE_Entities())
                {
                    var oData = (from a in db.OINV
                                 join b in db.OSLP on a.SlpCode equals b.SlpCode into bb
                                 from b in bb.DefaultIfEmpty()
                                 join c in db.OCRD on a.CardCode equals c.CardCode into cc
                                 from c in cc.DefaultIfEmpty()
                                 where 1 == 1

GeoCodingTest/Views/GeoCoding/BillingInfo.cshtml
@model GeoCodingTest.Models.L1.mWGE

<script type="text/javascript">
    function back() {
        window.history.back();
    }
</script>

<body onload="onload();">
    <div class="row">
        <div class="col-sm-6">

            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">ใบวางบิล</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>

                @if (Model != null && Model.ListOINV != null && Model.ListOINV.Count > 0)
                {
                    <div class="box-body">

                        <table id="odgvData" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                            <thead>
                                <tr role="row">
                                    <th>หัวข้อ</th>
                                    <th>รายละเอียด</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.ListOINV != null && Model.ListOINV.Count > 0)
                                {
                                    foreach (var oItem in Model.ListOINV)
                                    {
                                        if (Session["Name"].ToString() != "")
                                        {
                                            decimal a = oItem.Total ?? 0;
                                            var b = string.Format("{0:n}", Math.Round(a, 2));

                                            string c = oItem.DocDate.Value.ToString("dd/MM/yyyy");

                                            string d = oItem.DocDueDate.Value.ToString("dd/MM/yyyy");

                                            <tr>
                                                <th>ใบส่งของ</th>
                                                <td id="invno">@oItem.DocNum</td>
                                            </tr>
                                            <tr>
                                                <th>รหัส CP</th>
                                                <td id="fathercode">@oItem.FatherCard</td>
                                            </tr>
                                            <tr>
                                                <th>รหัสลูกค้า</th>
                                                <td id="cardcode">@oItem.CardCode</td>
                                            </tr>
                                            <tr>
                                                <th>ชื่อลูกค้า</th>
                                                <td id="cardname">@oItem.CardName</td>
                                            </tr>
                                            <tr>
                                                <th>ที่อยู่ลูกค้า</th>
                                                <td id="invno">@oItem.Address</td>
                                            </tr>
                                            <tr>
                                                <th>วันที่บิล (เดือน/วัน/ปี)</th>
                                                <td id="datebill">@c</td>
                                            </tr>
                                            <tr>
                                                <th>จำนวนเงิน(บาท)</th>
                                                <td id="total">@b</td>
                                            </tr>
                                            <tr>
                                                <th>วันที่มอบหมายงาน (เดือน/วัน/ปี)</th>
                                                <td id="duedatebill">@d</td>
                                            </tr>
                                            <tr style="display:none;">
                                                <td id="name" style="display:none;">@Session["Name"].ToString()</td>
                                            </tr>
                                            <tr style="display:none;">
                                                <td id="code" style="display:none;">@Session["Code"].ToString()</td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                }

                <div class="box-footer">
                    <button type="submit" class="btn btn-info " onclick="back();">ย้อนกลับ</button>
                </div>
            </div>
        </div>
    </div>
</body>

GeoCodingTest/Views/GeoCoding/Delivery.cshtml
<form id="form1" runat="server">
    <div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript">

        var optionsRadios1;
        var remark;
        var name;
        var code;
        var bank;

        function getLocation() {

            code = document.getElementById("Code").innerText;
            name = document.getElementById("Name").innerText;
            remark = document.getElementById("Remark").value;
            optionsRadios1 = $('input[name="optionsRadios1"]:checked').val(); //get value from radio button
            bank = document.getElementById("Bank").value;

            var message1 = "ยืนยันการบันทึก?";
            var r = confirm(message1);

            if (r == true) {
                if (name != "" && optionsRadios1 != null) {
                    if (navigator.geolocation) {
                        navigator.geolocation.getCurrentPosition(showPosition, showError);
                    }
                    else { alert("Geolocation is not supported by this browser."); }
                }
                else {
                    alert("ตัวเลือกห้ามว่าง!!");
                }
            }
            else {

            }           
        }

        function showPosition(position) {

            $.ajax({
                url: '@Url.Action("getDelivery","GeoCoding")',
                type: "POST",
                dataType: "json",
                data: JSON.stringify({

                    location: "Latitude: " + position.coords.latitude +
                        ",Longitude: " + position.coords.longitude + ",Accuracy:" + position.coords.accuracy + ","
                        + name + "," + code + "," + optionsRadios1,
                    Remark: remark,
                    Bank: bank
                }),
                contentType: 'application/json',
                complete: function () {
                    //alert('Success!');
                    window.location.href = '/Home/Index/';
                }
            });
            
        }

        function showError(error) {
            switch (error.code) {
                case error.PERMISSION_DENIED:
                    x.innerHTML = "User denied the request for Geolocation."
                    break;
                case error.POSITION_UNAVAILABLE:
                    x.innerHTML = "Location information is unavailable."
                    break;
                case error.TIMEOUT:
                    x.innerHTML = "The request to get user location timed out."
                    break;
                case error.UNKNOWN_ERROR:
                    x.innerHTML = "An unknown error occurred."
                    break;
            }

            window.location.href = '/GeoCoding/Other/';
        }

        function yesnoCheck() {
            if (document.getElementById('optionsRadios1').checked) {
                document.getElementById('ifMoney').style.display = 'block';
            }
            else {
                document.getElementById('ifMoney').style.display = 'none';
            }

        }

    </script>
</form>

<div class="row">
    <div class="col-sm-12">

        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">รับส่งเอกสาร</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="box-body">
                <div class="form-group">
                    <span style="display:none" id="Name">@Session["Name"].ToString()</span>
                    <span style="display:none" id="Code">@Session["Code"].ToString()</span>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios1" id="optionsRadios1" value="1" onclick="javascript:yesnoCheck();">
                            เข้าเช็ค
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios1" id="optionsRadios2" value="2" onclick="javascript:yesnoCheck();">
                            ส่งไปรษณีย์
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios1" id="optionsRadios3" value="3" onclick="javascript:yesnoCheck();">
                            ส่งเอกสาร
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios1" id="optionsRadios4" value="4" onclick="javascript:yesnoCheck();">
                            อื่นๆ ระบุ
                        </label>
                    </div>
                </div>
                <div class="col-sm-12" id="ifMoney" style="display:none">
                    <div>
                        <label>ธนาคาร :</label>
                        <select id="Bank" class="form-control">
                            <option>-</option>
                            <option value="KBANK">กสิกรไทย</option>
                            <option value="SCB">ไทยพาณิชย์</option>
                            <option value="BBL">กรุงเทพ</option>
                            <option value="TMB">ทีเอ็มบี</option>
                            <option value="BAY">กรุงศรีอยุธยา</option>
                            <option value="CITI">ซิตี้แบงก์</option>
                            <option value="GSB">ออมสิน</option>
                            <option value="KTB">กรุงไทย</option>
                            <option value="TBANK">ธนชาต</option>
                            <option value="HSBC">ธนาคารฮ่องกงและเซี้ยงไฮ้ (HSBC)</option>
                            <option value="UOB">ยูโอบี (UOB)</option>
                            <option value="BOA">แบงก์ออฟอเมริกา (BOA)</option>
                            <option value="CIMB">ธนาคารซีไอเอ็มบีไทย (CIMB)</option>
                            <option value="SCBT">ธนาคารสแตนดาร์ดชาร์เตอร์ด (SCBT)</option>
                            <option value="TTB">ธนาคารทีเอ็มบีธนชาต (TTB)</option>
                            <option value="Other Bank">ธนาคารอื่น</option>
                        </select>
                    </div><br />
                </div>
                <div class="form-group col-sm-12">
                    <label>หมายเหตุ</label>
                    <textarea class="form-control" name="Remark" id="Remark" rows="5" placeholder="หมายเหตุ..."></textarea>
                </div>
                <button type="submit" class="btn btn-info " onclick="getLocation();">บันทึก</button>
            </div>            
            <div class="box-footer">


            </div>
        </div>
    </div>
</div>

GeoCodingTest/Views/GeoCoding/Other2.cshtml
@model GeoCodingTest.Models.L1.mWGE

<form id="form1" runat="server">
    <div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript">

        var optionsRadios1;
        var remark;
        var name;
        var code;
        var invno;
        var cardcode;
        var cardname;
        var address;
        var docdate;
        var docduedate;
        var total;
        var total2;

        function getLocation() {

            name = document.getElementById("Name").innerText;
            code = document.getElementById("Code").innerText;
            invno = document.getElementById("InvNo").innerText;
            remark = document.getElementById("Remark").value;
            optionsRadios1 = $('input[name="optionsRadios1"]:checked').val(); //get value from radio button
            cardcode = document.getElementById("CardCode").innerText;
            cardname = document.getElementById("CardName").innerText;
            address = document.getElementById("Address").innerText;
            docdate = document.getElementById("DocDate").innerText;
            docduedate = document.getElementById("DocDueDate").innerText;
            total = document.getElementById("Total").innerText;
            total2 = total.replace(',', ''); //

            //alert(optionsRadios1);
            //cardcode = document.getElementById("cardcode").innerText;
            //cardname = document.getElementById("cardname").innerText;
            //invno = document.getElementById("invno").innerText;
            //datebill = document.getElementById("datebill").innerText;
            //datebill1 = datebill.toString("dd/MM/yyyy");
            //total = document.getElementById("total").innerText;
            //duedatebill = document.getElementById("duedatebill").innerText;
            //duedatebill1 = duedatebill.toString("dd/MM/yyyy");
            //name = document.getElementById("name").innerText;
            //code = document.getElementById("code").innerText;
            //typeid = document.getElementById("typeid").innerText;

            var message1 = "ยืนยันการบันทึก?";
            var r = confirm(message1);

            if (r == true) {
                if (name != "" && optionsRadios1 != null) {
                    if (navigator.geolocation) {
                        navigator.geolocation.getCurrentPosition(showPosition, showError);
                    }
                    else { alert("Geolocation is not supported by this browser."); }
                }
                else {
                    alert("ตัวเลือกห้ามว่าง!!");
                }
            }
            else {

            }            
        }

        function showPosition(position) {

            $.ajax({
                url: '@Url.Action("getOther2","GeoCoding")',
                type: "POST",
                dataType: "json",
                data: JSON.stringify({

                    location: "Latitude: " + position.coords.latitude +
                        ",Longitude: " + position.coords.longitude + ",Accuracy:" + position.coords.accuracy + ","
                        + name + ","+ code +"," + invno + "," + optionsRadios1 + "," + cardcode + "," + cardname
                        + "," + address + "," + total2
                    , DocDate1: docdate, DocDueDate1: docduedate,
                    Remark: remark
                }),
                contentType: 'application/json',
                complete: function () {
                    //alert('Success!');
                    window.location.href = '/Home/Index/';
                }
            });       
        }

        function showError(error) {
            switch (error.code) {
                case error.PERMISSION_DENIED:
                    x.innerHTML = "User denied the request for Geolocation."
                    break;
                case error.POSITION_UNAVAILABLE:
                    x.innerHTML = "Location information is unavailable."
                    break;
                case error.TIMEOUT:
                    x.innerHTML = "The request to get user location timed out."
                    break;
                case error.UNKNOWN_ERROR:
                    x.innerHTML = "An unknown error occurred."
                    break;
            }
        }

        function back() {
            window.history.back();
        }

    </script>
</form>

<div class="row">
    <div class="col-sm-6">

        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">อื่นๆ</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="box-body">
                
                @{ 
                    decimal a = Model.ListOINV[0].Total ?? 0;
                    var b = string.Format("{0:n}", Math.Round(a, 2));

                    string c = Model.ListOINV[0].DocDate.Value.ToString("dd/MM/yyyy");
                    string d = Model.ListOINV[0].DocDueDate.Value.ToString("dd/MM/yyyy");
                }

                <table id="odgvData" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <tbody>
                        <tr>
                            <th>เลขที่บิล</th>
                            <td id="InvNo">@Model.ListOINV[0].DocNum</td>
                        </tr>
                        <tr>
                            <th>รหัสลูกค้า</th>
                            <td id="FatherCode">@Model.ListOINV[0].FatherCard</td>
                        </tr>
                        <tr>
                            <th>รหัสลูกค้า</th>
                            <td id="CardCode">@Model.ListOINV[0].CardCode</td>
                        </tr>
                        <tr>
                            <th>ชื่อลูกค้า</th>
                            <td id="CardName">@Model.ListOINV[0].CardName</td>
                        </tr>
                        <tr>
                            <th>ที่อยู่ลูกค้า</th>
                            <td id="Address">@Model.ListOINV[0].Address</td>
                        </tr>
                        <tr>
                            <th>วันที่ออกบิล</th>
                            <td>@c</td>
                        </tr>
                        <tr style="display:none">
                            <th>วันที่ออกบิล</th>
                            <td id="DocDate">@Model.ListOINV[0].DocDate</td>
                        </tr>
                        <tr>
                            <th>วันที่มอบหมายงาน</th>
                            <td>@d</td>
                        </tr>
                        <tr style="display:none">
                            <th>วันที่มอบหมายงาน</th>
                            <td id="DocDueDate">@Model.ListOINV[0].DocDueDate</td>
                        </tr>
                        <tr>
                            <th>จำนวนเงิน (บาท)</th>
                            <td id="Total">@b</td>
                        </tr>
                        <tr>
                            <td style="display:none" id="Name">@Session["Name"].ToString()</td>
                        </tr>
                        <tr>
                            <td style="display:none" id="Code">@Session["Code"].ToString()</td>
                        </tr>

                    </tbody>
                </table>
                <br />
            </div>
            <div class="box-footer">
                <div class="form-group">
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios1" id="optionsRadios1" value="1">
                            เปลี่ยนบิล / เซ็นบิล
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios1" id="optionsRadios1" value="2">
                            รับบิล / รับใบเสร็จ / รับใบหัก ณ ที่จ่าย
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="optionsRadios1" id="optionsRadios1" value="3">
                            อื่นๆ ระบุ
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <label>หมายเหตุ</label>
                    <textarea class="form-control" name="remark" id="Remark" rows="5" placeholder="หมายเหตุ..."></textarea>
                </div>
                <button type="submit" class="btn btn-info " onclick="back();">ย้อนกลับ</button>
                <button type="submit" class="btn btn-info " onclick="getLocation();">บันทึก</button>
            </div>
        </div>
    </div>
</div>

GeoCodingTest/Views/GeoCoding/Popupview.cshtml
<div class="col-md-5 col-md-offset-3">
    <div class="form-group">
        <br />
        <img id="output" width="260" height="220" src="@Url.Content(Model.ListBW2[0].wk_path_img)" onClick="changePicture()" />
        <br /><br />
        <div>
            <h1>
                Test 2 ดกดหกดกหTeหกดกหดกหดdsadasdsadsadsasdsaกหst 3
            </h1>
        </div>
        <input type="file" name="file" id="choose file" accept="image/*" disabled onchange="loadFile(event)">
    </div>
</div>